[book]
authors = ["David Laehnemann"]
language = "en"
multilingual = false
src = "src"
title = "A collection of resources for data scientists (not only) in bioinformatics"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[output.html]
# Required: Your repository URL used in the link.
git-repository-url = "https://github.com/koesterlab/data-science-for-bioinfo"

# The text to use in the footer.
# The link text is marked by `[]`
open-on-text = "Want to add or correct something? [Edit this page on GitHub.]"

[output.linkcheck]
# Should we check links on the internet? Enabling this option adds a
# non-negligible performance impact
follow-web-links = false

# How should warnings be treated?
#
# - "warn" will emit warning messages
# - "error" treats all warnings as errors, failing the linkcheck
# - "ignore" will ignore warnings, suppressing diagnostic messages and allowing
#   the linkcheck to continuing
warning-policy = "error"
