name: set up, test and build with mdbook, deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  check_and_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true

      - name: Read versions.env
        id: versions
        run: |
          . .github/workflows/versions.env
          echo "mdbook_version=$MDBOOK_VERSION" >>$GITHUB_OUTPUT
          echo "opengh_version=$OPENGH_VERSION" >>$GITHUB_OUTPUT

      - name: Setup mdbook
        uses: jontze/action-mdbook@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Optional Plugins have to be enabled with a version
          mdbook-version: "${{ steps.versions.outputs.mdbook_version }}" # Use a semver compatible string
          use-opengh: true
          opengh-version: "${{ steps.versions.outputs.opengh_version }}"
      - name: Build mdbook (with checks)
        run: mdbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/html
